language: scala
matrix:
  include:
    - scala: 2.11.12
      env: PLAY_VERSION=2.5
      jdk: openjdk8
    - scala: 2.11.12
      env: PLAY_VERSION=2.6
      jdk: openjdk8
    - scala: 2.12.10
      env: PLAY_VERSION=2.6
      jdk: openjdk8
    - scala: 2.12.10
      env: PLAY_VERSION=2.7
      jdk: openjdk8

services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
