language: scala
matrix:
  include:
    - scala: 2.11.12
      env: PLAY_VERSION=2.5
      jdk: openjdk8
    - scala: 2.11.12
      env: PLAY_VERSION=2.6
      jdk: openjdk8
    - scala: 2.12.10
      env: PLAY_VERSION=2.6
      jdk: openjdk8
    - scala: 2.12.10
      env: PLAY_VERSION=2.7
      jdk: openjdk8

notifications:
  email:
    recipients:
    - platform-engineering@digital.hmrc.gov.uk
before_script:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5"
  - "echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list"
  - "sudo apt-get update"
  - "sudo apt-get install -y mongodb-org"
  - "sudo apt-get install -y mongodb-org=3.2.11 mongodb-org-server=3.2.11 mongodb-org-shell=3.2.11 mongodb-org-mongos=3.2.11 mongodb-org-tools=3.2.11"

  - "sleep 15" #mongo may not be responded directly. See http://docs.travis-ci.com/user/database-setup/#MongoDB
  - "mongo --version"
